import openpyxl

MAPEO = {
    "RODAMIENTOS": "RODAMIENTOS", "RODAMINETOS CENTRAL": "RODAMIENTOS",
    "BACE DE RODAMIENTO": "RODAMIENTOS", "COJINETES DE VIELA": "RODAMIENTOS",
    "COJINETES DE BANCADA": "RODAMIENTOS", "COJINETE AXIAL": "RODAMIENTOS",
    "COJINETE LEVA": "RODAMIENTOS",
    "CORREA VARIAS": "CORREAS Y CADENAS", "CORREA DISTRIBUCION": "CORREAS Y CADENAS",
    "CADENA DE DISTRIBUCION": "CORREAS Y CADENAS", "KIT DISTRIBUCION": "CORREAS Y CADENAS",
    "TESADOR GUIA CADENA": "CORREAS Y CADENAS", "TAPA DISTRIBUIDOR": "CORREAS Y CADENAS",
    "DISTRIBUIDORES": "CORREAS Y CADENAS", "POLEAS": "CORREAS Y CADENAS",
    "JALADORES": "CORREAS Y CADENAS", "ESPIRALES": "CORREAS Y CADENAS",
    "RETENES": "RETENES Y SELLOS", "ORING": "RETENES Y SELLOS",
    "ORING CALIPER": "RETENES Y SELLOS", "SELLO": "RETENES Y SELLOS",
    "SELLO DE BBA DE AGUA": "RETENES Y SELLOS", "SELLO TAPA VALANCIN": "RETENES Y SELLOS",
    "PRECINTOS": "RETENES Y SELLOS", "CORCHO": "RETENES Y SELLOS",
    "SHELLAC": "RETENES Y SELLOS", "SELLADOR DE RADIADOR": "RETENES Y SELLOS",
    "TRABACIL": "RETENES Y SELLOS", "CILICONA": "RETENES Y SELLOS",
    "ANILLAS": "EMPAQUETADURAS Y JUNTAS", "EMPAQUETADURA DE CULATA": "EMPAQUETADURAS Y JUNTAS",
    "EMPAQUETADURA DE MOTOR": "EMPAQUETADURAS Y JUNTAS", "EMPAQUE DE BALANCIN": "EMPAQUETADURAS Y JUNTAS",
    "JUNTAS": "EMPAQUETADURAS Y JUNTAS", "EMPAQUE CAÑO ESCAPE": "EMPAQUETADURAS Y JUNTAS",
    "EMPAQUE DE MULTIPLE": "EMPAQUETADURAS Y JUNTAS", "EMPAQUE TUBO ESCAPE": "EMPAQUETADURAS Y JUNTAS",
    "EMPAQUE DE CARTER": "EMPAQUETADURAS Y JUNTAS", "EMPAQUE DE ESCAPE": "EMPAQUETADURAS Y JUNTAS",
    "AMIENTO Y ASBESTO PARA EMPAQUES": "EMPAQUETADURAS Y JUNTAS",
    "AMORTIGUADORES": "AMORTIGUADORES Y SUSPENSION", "SOPORTE DE AMORTIGUADOR": "AMORTIGUADORES Y SUSPENSION",
    "MUÑON ESTABILIZADOR": "AMORTIGUADORES Y SUSPENSION", "BUJE BARRA ESTABILISADORA": "AMORTIGUADORES Y SUSPENSION",
    "PERNO ESTABILISADOR": "AMORTIGUADORES Y SUSPENSION", "TACOS DE SUSPENCION": "AMORTIGUADORES Y SUSPENSION",
    "BANDEJA-TIJERAL": "AMORTIGUADORES Y SUSPENSION", "BUJE DE BANDEJA": "AMORTIGUADORES Y SUSPENSION",
    "VASTAGOS HIDRAULICOS": "AMORTIGUADORES Y SUSPENSION", "BUJES DE MUELLE Y AMORTIGUADOR": "AMORTIGUADORES Y SUSPENSION",
    "PISTONES": "MOTOR", "VALVULAS": "MOTOR", "GUIADORES DE VALVULA": "MOTOR",
    "GUIADORES": "MOTOR", "CAMISAS": "MOTOR", "BUJE BIELA": "MOTOR",
    "SOPORTE DE MOTOR": "MOTOR", "CAPUCHONES": "MOTOR", "PRECAMARAS": "MOTOR",
    "PLATINO Y CONDENSADOR": "MOTOR", "TERMOSTATO": "MOTOR", "PLASTICO TERMOSTATO": "MOTOR",
    "PLANETARIOS": "MOTOR", "SATELITE": "MOTOR", "ENGRANAJE": "MOTOR",
    "ENGRANAJE BOMBA ACEITE": "MOTOR", "SINCRONIZADORES": "MOTOR",
    "PASTILLAS DE FRENO": "FRENOS", "BALATAS DE FRENO": "FRENOS", "DISCO DE FRENO": "FRENOS",
    "CILINDRO DE FRENO": "FRENOS", "BOMBAS DE FRENO": "FRENOS", "HIDROBACK DE FRENO": "FRENOS",
    "MANGUERAS DE FRENO": "FRENOS", "REPAROS BBA DE FRENO": "FRENOS",
    "REPARO CILINDRO DE FRENO": "FRENOS", "CALIPER": "FRENOS", "REPARO DE MORDAZA": "FRENOS",
    "TAMBORES": "FRENOS", "REGULADORES DE BALATAS": "FRENOS", "SEGUROS DE PASTILLAS": "FRENOS",
    "ROTORES": "FRENOS", "CUBETAS": "FRENOS",
    "DISCO EMBRAGUE": "EMBRAGUE", "BOMBAS DE EMBRAGUE": "EMBRAGUE",
    "REPARO DE BBA EMBRAGE": "EMBRAGUE", "REPARO DE BBA AUXILIAR": "EMBRAGUE",
    "BOMBA AUXILIAR EMBRAGUE": "EMBRAGUE", "BBA BBA DE EMBRAGUE": "EMBRAGUE",
    "EMBRAGUE DE VENTILADOR": "EMBRAGUE", "ORQUILLAS DE CAJA": "EMBRAGUE",
    "MUÑON DE DIRECCION": "DIRECCION", "ROTULAS": "DIRECCION",
    "CRUCETAS DIRECCION": "DIRECCION", "PRECAP DE CREMALLERA": "DIRECCION",
    "CREMALLERAS DE DIRECCION": "DIRECCION", "ACOPLE DIRECCION": "DIRECCION",
    "VOLANTE DE DIRECCION": "DIRECCION", "PRENSAS": "DIRECCION", "BUJES": "DIRECCION",
    "TRICETAS": "TRANSMISION", "CRUCETA DE CARDAN": "TRANSMISION",
    "ESPIGA DE CARDAN": "TRANSMISION", "YOKE": "TRANSMISION",
    "PASADOR DE CAJA": "TRANSMISION", "PASADOR DE PUNTA EJE": "TRANSMISION",
    "CANDADOS DE RUEDA": "TRANSMISION", "ESPIGA": "TRANSMISION",
    "FOCOS": "ELECTRICIDAD", "CABLES DE BUJIA": "ELECTRICIDAD", "BUJIAS": "ELECTRICIDAD",
    "BOBINAS": "ELECTRICIDAD", "RELAY": "ELECTRICIDAD", "FICHAS Y PORTA FUCIBLES": "ELECTRICIDAD",
    "FUSIBLES": "ELECTRICIDAD", "CABLES PARA LUZ": "ELECTRICIDAD",
    "INTERRUPTORES": "ELECTRICIDAD", "RECTIFICADORES": "ELECTRICIDAD",
    "FAROLES": "ELECTRICIDAD", "CARBONES": "ELECTRICIDAD", "ESCOBILLAS LIMPIA PARABRIS": "ELECTRICIDAD",
    "MODULOS": "ELECTRICIDAD", "REGULADORES": "ELECTRICIDAD", "BORNES": "ELECTRICIDAD",
    "COMUTADORES": "ELECTRICIDAD", "CHAPAS DE CONTACTO": "ELECTRICIDAD",
    "RESISTENCIA": "ELECTRICIDAD", "SENSOR": "ELECTRICIDAD", "SENSORES DE AIRE": "ELECTRICIDAD",
    "AMPERIMETROS": "ELECTRICIDAD", "INDUZIDOS": "ELECTRICIDAD", "MOTOR VENTILADOR": "ELECTRICIDAD",
    "ARRANQUE": "ELECTRICIDAD", "BENDIX DE ARRANQUE": "ELECTRICIDAD",
    "SELENOIDE DE ARRANQUE": "ELECTRICIDAD", "SOLENOIDE DE ARRANQUE": "ELECTRICIDAD",
    "ALTERNADORES": "ELECTRICIDAD", "HALOGENO": "ELECTRICIDAD",
    "PRECALENTADORES": "ELECTRICIDAD", "VIBRADOR FLEXIBLE": "ELECTRICIDAD",
    "BOMBA ELECTRICA": "ELECTRICIDAD",
    "FILTROS DE AIRE": "FILTROS", "FILTROS DE GASOLINA": "FILTROS",
    "FILTROS DE ACEITE": "FILTROS", "FILTRO DE DIESEL": "FILTROS",
    "BOMBAS DE GASOLINA": "COMBUSTIBLE E INYECCION", "BOMBA ACEITE": "COMBUSTIBLE E INYECCION",
    "BOMBA HIDRAULICA": "COMBUSTIBLE E INYECCION", "REPARO BOMBA IYECTORA": "COMBUSTIBLE E INYECCION",
    "BOMBIN DE DIESEL": "COMBUSTIBLE E INYECCION", "REPARO BOMBA AGUA": "COMBUSTIBLE E INYECCION",
    "REPRARO BOMBA IDRAULICA": "COMBUSTIBLE E INYECCION", "LIMPIA INYECTORES": "COMBUSTIBLE E INYECCION",
    "GOMA PURIFICADOR": "COMBUSTIBLE E INYECCION", "MANGUERA PURIFICADOR": "COMBUSTIBLE E INYECCION",
    "NIPLES Y CONECTORES PARA GAS": "COMBUSTIBLE E INYECCION",
    "REPARO DE CARBURADOR": "COMBUSTIBLE E INYECCION", "CARBURADORES": "COMBUSTIBLE E INYECCION",
    "ACEITES": "LUBRICANTES Y FLUIDOS", "GRASAS": "LUBRICANTES Y FLUIDOS",
    "LIQUIDOS": "LUBRICANTES Y FLUIDOS", "ANTICONGELANTE": "LUBRICANTES Y FLUIDOS",
    "AGUA DESTILADA": "LUBRICANTES Y FLUIDOS", "ADITIVOS": "LUBRICANTES Y FLUIDOS",
    "ADICTIVOS": "LUBRICANTES Y FLUIDOS", "ELEVAROR DE OCTANAJE": "LUBRICANTES Y FLUIDOS",
    "POXIPOL": "LUBRICANTES Y FLUIDOS", "POXILINA": "LUBRICANTES Y FLUIDOS",
    "PASTA DE PULIR": "LUBRICANTES Y FLUIDOS", "RENOVADOR DE LLANTAS": "LUBRICANTES Y FLUIDOS",
    "BOMBAS DE AGUA": "ENFRIAMIENTO", "MANGUERAS DE RADIADOR": "ENFRIAMIENTO",
    "RADIADORES": "ENFRIAMIENTO", "TAPAS DE RADIADOR": "ENFRIAMIENTO",
    "ASPAS": "ENFRIAMIENTO", "VENTILADORES": "ENFRIAMIENTO",
    "CHICOTILLO ASELERADOR": "CHICOTILLOS Y CABLES", "CHICOTILLO EMBRAGUE": "CHICOTILLOS Y CABLES",
    "CHICOTILLO VELOCIMETRO": "CHICOTILLOS Y CABLES", "CHICOTILLO FRENO": "CHICOTILLOS Y CABLES",
    "CHICOTILLO CAJA": "CHICOTILLOS Y CABLES", "CHICOTILLO CAPOT": "CHICOTILLOS Y CABLES",
    "CREMALLERAS DE PUERTA": "CARROCERIA", "CILINDROS DE PUERTA": "CARROCERIA",
    "CHAPA DE PUERTA": "CARROCERIA", "CHAPA MALETERO": "CARROCERIA",
    "GANCHOS DE PURTA": "CARROCERIA", "GOMAS PARA PUERTAS": "CARROCERIA",
    "REPARO CREMALLERA PUERTA": "CARROCERIA", "MANIVELAS": "CARROCERIA",
    "ESPEJOS": "CARROCERIA", "PINTURAS": "CARROCERIA", "CANTONERAS": "CARROCERIA",
    "VICEL DE FAROL": "CARROCERIA", "CAMARAS": "CARROCERIA", "TUNEADOS": "CARROCERIA",
    "AMBIENTADORES": "CARROCERIA", "BOTIQUIN PRIMEROS AUXILIOS": "CARROCERIA",
    "TRIANGULO": "CARROCERIA", "BOTONES": "CARROCERIA",
    "ARANDELA": "FIJACIONES Y VARIOS", "ABRAZADERAS": "FIJACIONES Y VARIOS",
    "PERNOS": "FIJACIONES Y VARIOS", "TUERCAS": "FIJACIONES Y VARIOS",
    "NIPLES": "FIJACIONES Y VARIOS", "SEGUROS": "FIJACIONES Y VARIOS",
    "TAPONES EN GRAL.": "FIJACIONES Y VARIOS", "TAPA DE TANQUE": "FIJACIONES Y VARIOS",
    "CAÑERIAS": "FIJACIONES Y VARIOS", "MANGUERAS": "FIJACIONES Y VARIOS",
    "CINTAS": "FIJACIONES Y VARIOS", "TUBO CORRUGADO": "FIJACIONES Y VARIOS",
    "BOQUILLAS": "FIJACIONES Y VARIOS", "GOMAS": "FIJACIONES Y VARIOS",
    "BOCINAS": "FIJACIONES Y VARIOS", "UÑETA": "FIJACIONES Y VARIOS",
    "LLAVES": "FIJACIONES Y VARIOS", "DADOS": "FIJACIONES Y VARIOS",
    "VASOS": "FIJACIONES Y VARIOS", "AGUJAS": "FIJACIONES Y VARIOS",
    "SUPLES": "FIJACIONES Y VARIOS", "SOPORTE ESCAPE": "FIJACIONES Y VARIOS",
    "PEGAMENTOS": "FIJACIONES Y VARIOS", "GOTITA": "FIJACIONES Y VARIOS",
    "BOTELLONES": "FIJACIONES Y VARIOS", "GENERAL": "FIJACIONES Y VARIOS",
    "VULVOS": "FIJACIONES Y VARIOS", "PLASTIGAGE": "FIJACIONES Y VARIOS",
}

CATEGORIAS_FINALES = sorted(set(MAPEO.values()))

wb = openpyxl.load_workbook("backend/example_tables/INVENTARIO_UNIFICADO.xlsx", data_only=True)
ws = wb.active

sin_mapeo = set()
for r in range(2, ws.max_row + 1):
    cat_orig = ws.cell(r, 12).value
    if cat_orig:
        cat_norm = str(cat_orig).strip().upper()
        cat_nueva = MAPEO.get(cat_norm)
        if cat_nueva:
            ws.cell(r, 12).value = cat_nueva
        else:
            sin_mapeo.add(cat_norm)
    ws.cell(r, 18).value = 0
    ws.cell(r, 19).value = 0

wb.save("backend/example_tables/INVENTARIO_UNIFICADO.xlsx")

print("Excel actualizado.")
print(f"Total categorias consolidadas: {len(CATEGORIAS_FINALES)}")
for c in CATEGORIAS_FINALES:
    print(f"  - {c}")
if sin_mapeo:
    print(f"\nSin mapeo ({len(sin_mapeo)}): {sin_mapeo}")
